<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="asd1550po01976" name="Default test" tests="10" failures="1" timestamp="5 Jul 2016 07:19:09 GMT" time="128.118" errors="0">
  <testcase name="testOne" time="11.917" classname="GithubAutomation.AppTest"/>
  <testcase name="testTwo" time="1.475" classname="GithubAutomation.AppTest"/>
  <testcase name="testThree" time="2.486" classname="GithubAutomation.AppTest"/>
  <testcase name="testFour" time="6.226" classname="GithubAutomation.AppTest"/>
  <testcase name="testFive" time="8.548" classname="GithubAutomation.AppTest"/>
  <testcase name="testSix" time="1.207" classname="GithubAutomation.AppTest"/>
  <testcase name="testSeven" time="14.377" classname="GithubAutomation.AppTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at GithubAutomation.AppTest.testSeven(AppTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- testSeven -->
  <testcase name="testEight" time="0.0" classname="GithubAutomation.AppTest">
    <skipped/>
  </testcase> <!-- testEight -->
  <testcase name="testNine" time="0.0" classname="GithubAutomation.AppTest">
    <skipped/>
  </testcase> <!-- testNine -->
  <testcase name="testTen" time="0.0" classname="GithubAutomation.AppTest">
    <skipped/>
  </testcase> <!-- testTen -->
</testsuite> <!-- Default test -->
